# Generated by Django 2.2.10 on 2020-04-06 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=500, verbose_name='room')),
                ('red_points', models.IntegerField(default=0)),
                ('blue_points', models.IntegerField(default=0)),
                ('round_done', models.BooleanField(default=True)),
                ('current_round', models.IntegerField(choices=[(0, 'pregame'), (1, 'round one'), (2, 'round two'), (3, 'round three'), (4, 'postgame')], default=0)),
                ('active_guessing', models.BooleanField(default=False)),
                ('current_guessing_team', models.CharField(blank=True, choices=[('red', 'red'), ('blue', 'blue')], max_length=50, null=True)),
                ('current_word', models.CharField(blank=True, choices=[('red', 'red'), ('blue', 'blue')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('clue_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clue_giver', to=settings.AUTH_USER_MODEL, verbose_name='clue_giver')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('red', 'red'), ('blue', 'blue')], max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_scored', models.IntegerField(choices=[(0, 'pregame'), (1, 'round one'), (2, 'round two'), (3, 'round three'), (4, 'postgame')], default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Word')),
            ],
        ),
    ]
