# Generated by Django 2.2.10 on 2020-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_player_point_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.CharField(max_length=500, unique=True, verbose_name='room'),
        ),
    ]
