# Generated by Django 2.2.10 on 2020-04-07 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='clue_giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_giver', to=settings.AUTH_USER_MODEL, verbose_name='clue_giver'),
        ),
    ]
