# Generated by Django 2.2.10 on 2020-04-09 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200407_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-created_timestamp',), 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='game',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created_timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='round_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='round_start_time'),
        ),
    ]
