# Generated by Django 2.2.10 on 2020-04-09 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200409_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_length',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='room'),
        ),
    ]
