# Generated by Django 2.2.10 on 2020-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200409_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('blue', 'blue')], db_index=True, max_length=500, null=True),
        ),
    ]
