# Generated by Django 2.2.10 on 2020-04-09 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20200409_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='clue_giver',
        ),
        migrations.AddField(
            model_name='game',
            name='blue_giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_giver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='red_giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_giver', to=settings.AUTH_USER_MODEL),
        ),
    ]
