# Generated by Django 2.2.10 on 2020-04-09 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200409_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined_timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='joined_timestamp'),
            preserve_default=False,
        ),
    ]
