# Generated by Django 2.2.10 on 2020-04-09 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_player_joined_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='remaining_seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
