# Generated by Django 2.2.10 on 2020-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200409_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(choices=[(1, 'round one'), (2, 'round two'), (3, 'round three'), (4, 'postgame')], default=1),
        ),
        migrations.AlterField(
            model_name='point',
            name='round_scored',
            field=models.IntegerField(choices=[(1, 'round one'), (2, 'round two'), (3, 'round three'), (4, 'postgame')], default=1),
        ),
    ]
