# Generated by Django 2.2.10 on 2020-04-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200409_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_live_round',
            new_name='is_live_turn',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='round_length',
            new_name='turn_length',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='round_start_timeint',
            new_name='turn_start_timeint',
        ),
    ]
