# Generated by Django 2.2.10 on 2020-04-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200409_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_word',
        ),
    ]
