# Generated by Django 2.2.10 on 2020-04-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_game_current_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='blue_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='red_points',
        ),
    ]
