# Generated by Django 2.2.10 on 2020-04-10 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200409_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_word_length',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
