# Generated by Django 2.2.10 on 2020-04-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200410_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='team',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue')], db_index=True, default='red', max_length=500),
            preserve_default=False,
        ),
    ]
