# Generated by Django 2.2.10 on 2020-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200410_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='point',
            name='round_scored',
            field=models.IntegerField(default=0),
        ),
    ]
