# Generated by Django 2.2.10 on 2020-04-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_game_max_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='max_words',
            new_name='words_per_player',
        ),
    ]
